# Generated by Django 4.2.7 on 2023-11-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0012_servicepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='short_description',
            field=models.CharField(max_length=255),
        ),
    ]
