# Generated by Django 4.2.7 on 2023-11-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0013_alter_servicepost_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepost',
            old_name='image',
            new_name='Serviceimage',
        ),
    ]
