# Generated by Django 4.2.7 on 2023-11-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0014_rename_image_servicepost_serviceimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepost',
            old_name='short_description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='servicepost',
            old_name='Serviceimage',
            new_name='Service_image',
        ),
        migrations.RenameField(
            model_name='servicepost',
            old_name='slug',
            new_name='Title_Url',
        ),
    ]
