# Generated by Django 4.2.7 on 2023-11-16 11:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0015_rename_short_description_servicepost_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepost',
            name='content',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
