# Generated by Django 4.2.7 on 2023-11-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0016_servicepost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepost',
            name='Service_icon',
            field=models.ImageField(default=1, upload_to='Admin/Serviceimages/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='Service_image',
            field=models.ImageField(upload_to='Admin/Serviceicons/'),
        ),
    ]
