# Generated by Django 4.2.7 on 2023-11-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0018_visitorenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gallery_Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='VisitorEnquiry',
        ),
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(blank=True, to='FocalNest.galleryimage'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FocalNest.servicepost'),
        ),
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together={('service', 'Gallery_Title')},
        ),
    ]
