# Generated by Django 4.2.7 on 2023-11-19 02:39

import FocalNest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0019_gallery_galleryimage_delete_visitorenquiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=models.ImageField(default=1, upload_to=FocalNest.models.gallery_image_path),
            preserve_default=False,
        ),
    ]
