# Generated by Django 4.2.7 on 2023-11-19 02:51

import FocalNest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0020_remove_gallery_images_gallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=FocalNest.models.gallery_image_path),
        ),
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(to='FocalNest.galleryimage'),
        ),
    ]
