# Generated by Django 4.2.7 on 2023-11-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0021_remove_gallery_images_alter_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
