# Generated by Django 4.2.7 on 2023-11-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0024_alter_gallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
    ]
