# Generated by Django 4.2.7 on 2023-11-19 04:47

import FocalNest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0025_remove_gallery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=models.ImageField(default=2, upload_to=FocalNest.models.gallery_image_path),
            preserve_default=False,
        ),
    ]
