# Generated by Django 4.2.7 on 2023-11-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0027_alter_gallery_unique_together_galleryimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='Admin/GalleryImages/'),
        ),
    ]
