# Generated by Django 4.2.7 on 2023-11-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0028_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together={('service', 'Gallery_Title')},
        ),
        migrations.AlterUniqueTogether(
            name='galleryimage',
            unique_together={('gallery', 'image')},
        ),
    ]
