# Generated by Django 4.2.7 on 2023-11-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0029_alter_gallery_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='galleryimage',
            unique_together=set(),
        ),
    ]
