# Generated by Django 4.2.7 on 2023-11-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0030_alter_galleryimage_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='Blog_title',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='slug',
            new_name='Title_url',
        ),
    ]
