# Generated by Django 4.2.7 on 2023-11-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0031_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('interested_in', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
