# Generated by Django 4.2.7 on 2023-11-21 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FocalNest', '0032_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='interested_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FocalNest.servicepost'),
        ),
    ]
